### ISSUE TITLE
detect and warn about broken cycle periods

### ISSUE THREAD

**Issue by bschindler** [KDAB/hotspot#124] opened 2018-02-12 12:48 UTC
May be I am just misusing the tool, but I feel like this is a bug: 

So I profile an app, I filter the main thread and look at the flame graph and get this (which looks wrong): 
![screenshot_20180212_133913](https://user-images.githubusercontent.com/2241296/36097283-98b6c72c-0ffa-11e8-8943-0c6d79ef2dc8.png)

I then select a range in the timeline view (a very useful feature btw, thanks a lot for this) and then I get this flamegraph:

![screenshot_20180212_133819](https://user-images.githubusercontent.com/2241296/36097308-ba6446d8-0ffa-11e8-8d7c-92452f9fa0b0.png)

In my understanding, a filtered flamegraph should contain a pure subset of the unfiltered one so I do not understand the reason for this discrepancy. The TetMeshDistanceField constructor (yellow in the second screenshow) takes a very significant amount of time in the lower timeline so I see no reason why it should not appear

**Comment by milianw** [comment] 2018-02-12 21:49
What exactly is the bug? That you don't see `TetMeshDistanceField` in the first screenshot? The first one shows a total cost of 1E13, the lower one of 1E10 - so there are quite a few orders of magnitude difference. Maybe the things you are looking at in the bottom are dwarfed by the other hotspots shown in the first graph?

**Comment by bschindler** [comment] 2018-02-12 22:05
Then I think this number is calculated the wrong way. The selection you see in the lower screenshot really does take computation wise about 40-50% of the time in the selected thread (its what I wanted to profile after all) and not like 0.001%. 
Also note that the timeline in the bottom screenshot does not have a different zoom level than in the screenshot above. Since the thread is busy more or less 100% in the first screenshot, I would expect that about 60% of the samples are filtered out by the selection (or about 40% remain). This also more or less confirms my expectation of this code taking roughly 40% of the time. 
So where does this order of magnitude come from? It really does not make sense. 

Also, if I extend the selected range just so that it extends into the inactive regions seen in the upper screenshot (by increasing the selection just slightly on both ends), the flamegraph completely changes from what you see in the lower screenshot to a flamegraph containing only mono_class_get_methods and nothing else at all.

**Comment by milianw** [comment] 2018-02-12 22:49
Time != cycles.

One common issue that I see is that the cycles measured by perf are pretty bogus. I suspect you recorded with the default settings, giving you a frequency mode recording. What happens when you use `perf record -c 3000000 --call-graph dwarf` or similar instead?

Also, what does `perf report` show you? Do you see the same issue there? Also try to  have a look at `perf script`, I suspect you get a few bogus samples for e.g. `mono_class_get_methods` that completely throw off the weighting by cycle value. We don't offer a different weighting method yet (like, per sample - that's tracked by #105).

**Comment by bschindler** [comment] 2018-02-13 07:49
I do admit that my understanding of perf is still quite limited. My record command was `perf record --call-graph dwarf pid` and then pressed Ctrl+c to sample roughly the period of interest in the lifetime of the application. 
I do have two questions - what does the -c parameter do? The manpage is super scarce on details what it actually means. I'll only be at the relevant machine on thu, but I do suspect that perf report will show me the same result as I used to have similar issues when using perf report to analyze the same application. Do you have any info on where such bogus samples could originate from/why they happen? 

Thanks

**Comment by milianw** [comment] 2018-02-13 09:27
If it's the issue that I think about, then you can find some more information about it here: 

https://www.spinics.net/lists/linux-perf-users/msg03486.html

Note that it never was really acknowledged by the perf maintainer(s). I still see it sometimes, so I think it's still a bug with the frequency mode somewhere.

A short explanation of the different modes in my own words:

`-F 1000` (the default) tries to automatically configure the PMU event counter such that you get roughly 1000 samples per second. If you look at the `perf script` output, you'll see how it changes the counter interval at which the PMU raises the next interrupt, so the cycle counts for the individual samples are all slightly different. In the ideal case, eventually a rough steady state is reached and all samples have about the same value with slight deviations.

`-c 3000000` disables the frequency mode and instead uses a hardcoded event counter value at which an interrupt is triggered by the PMU. As such, `perf script` shows that the cycle values for all samples are equal - 3000000. I pick that value, as it gives me roughly 1000 samples per second for a 3GHz CPU.

**Comment by bschindler** [comment] 2018-02-15 16:24
Thanks for this link, yes it very much looks like I'm being hit by the same snag. I loaded perf data created using default options, found a function which seems to take a lot of time but seems off, did a perf script to find the events and sure enough, I found this: 

fuse 27625 17552.168142550: 17592231817274 cycles:pp: 

while the next one is: 

fuse 27625 17552.210048903:     333368 cycles:pp: 

Setting -c 30000000 indeed gets rid of this issue and the graph now looks much more in line with what I'd expect.

**Comment by milianw** [comment] 2018-11-14 16:34
@bschindler  can you still reproduce the perf issue with a recent kernel? I hope that this actually got fixed without me noticing. At least, I can't reproduce it currently!

**Comment by bschindler** [comment] 2018-11-14 21:50
I don't have access to the machine where I had the issue anymore, feel free to close

**Closed** 2022-06-15 16:27 UTC
