### ISSUE TITLE
Default sort-order in flamegraph is by name, good choice ?

### ISSUE THREAD

**Issue by mulle-nat** [KDAB/hotspot#277] opened 2020-12-28 13:10 UTC
As I understand it, the symbols in the flamegraph are sorted by "name". So if I have three function **a** (fast), **b** (medium), **c** (slow) called from **main** in the order (c,a,b) the output in the flamegraph will be (a,b,c) nevertheless. 

![image](https://user-images.githubusercontent.com/1381995/103216213-c862ef80-4915-11eb-8cd4-797c9b01cf9e.png)

If I make c faster, the order stays the same. So it is sorted by "name".

![image](https://user-images.githubusercontent.com/1381995/103216344-22fc4b80-4916-11eb-92d3-73caea937f0b.png)

If the flamegraph would be sorted by "timestamp" in the order of appearance in the perf.data, the order would be (c,a,b), which is, what I would have expected initally. A possibly less confusing order could be order by "weight" (c,b,a)

But that's just my opinion. :smiley: 

Here's my demo code:
```
// cc -O0 -g -o  x main.c 
#include <stdlib.h>


static int   burn( int r)
{
   long  i;

   for( i = 0; i < 1000; i++)
      r += rand();
   return( r);
}


int  a( int r)
{
   int   i;

   for( i = 0; i < 10000 / 4; i++)
      r += burn( r);
   return( r);
}


int  b( int r)
{
   int   i;

   for( i = 0; i < 10000 / 2; i++)
      r += burn( r);
   return( r);
}


int  c( int r)
{
   int   i;

   for( i = 0; i < 10000; i++)
      r += burn( r);
   return( r);
}


int   main( int argc, char *argv[])
{
   int  r;

   r  = argc;
   r += c( r);
   r += a( r);
   r += b( r);
   return( r);
}
```

**Comment by milianw** [comment] 2020-12-28 15:00
The order on the x-axis of a flamegraph is undefined. Using time would move this more into flamechart territory, which is not (yet?) supported by hotspot. I chose to order by name to make the order somewhat stable, which simplifies comparisons between multiple runs. Esp. when you have multiple threads involved, using time could lead to random jumps in the flame graph. Sorting by weight would also make it harder to compare before/after profiles, as depending on the impact of your change, the pillar would "randomly" move in the graph.

I'll close this, as imo it works as intended. It seems like you just need to get used to the data visualization :shrug:

**Closed by milianw** 2020-12-28 15:00 UTC

**Comment by milianw** [comment] 2020-12-28 15:02
See also: http://www.brendangregg.com/flamegraphs.html

> The x-axis shows the stack profile population, sorted alphabetically (it is not the passage of time),
