### ISSUE TITLE
in BottomUp, reallocate time spent in ? functions to known functions

### ISSUE THREAD

**Issue by grandinj** [KDAB/hotspot#384] opened 2022-05-21 15:47 UTC
So for some context: 

(1) I'm analysing a very large application (LibreOffice), that includes a boatload of 3rd party libraries, and calls into a boatload of OS libraries, for which symbol information is not always available (even if I have installed the debug data)

(2) My profile is nastily flat, so I'm guessing very small wins.

So in my Bottom Up tab, I often have a tree that looks like:

    ?
    +---foo()

So what I would like, is to have the time from ? treated as if it originated from foo()

The reason for that, is that from my perspective the first known function is the most interesting thing, and I'd like to see the time treated as if spent there.

I often have to navigate down several layers of ? until I see a function that is already present at the top level of the Bottom Up tab, and I've to know how much __actual__ time is spent in that function (as a proportion of total time)

Thanks!

**Comment by milianw** [comment] 2022-06-15 15:00
this is a duplicate of https://github.com/KDAB/hotspot/issues/186

**Closed by milianw** 2022-06-15 15:00 UTC
Labels: enhancement
