### ISSUE TITLE
Disassembly view: Are assembly lines expected to have near zero cycles?

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#429] opened 2022-11-28 09:45 UTC
This issue is mostly a question.
Running on Debian with kernel 5.15 and perf 5.15 on this machine.

In an example recording done with `perf record --call-graph dwarf,8192 -z --sample-cpu ./dice` I see only two lines in Disassembly with a cost attached, but the Source view shows much more (and strangely shows an unreasonable high inclusive cost on a `return` line):

![example disassembly](https://user-images.githubusercontent.com/6699539/204245733-bd5c9ae8-8085-4f47-8f03-244a3cd23866.png)

Are those costs "expected"?

**Comment by milianw** [comment] 2022-11-28 11:00
please attach the source code to reproduce this, as-is it's unclear whether there should be more or not. do you just have to scroll on the RHS maybe? could also be due to inlining, i.e. most of the cost is in other places potentially?

**Comment by milianw** [comment] 2024-09-02 06:49
I believe this is a duplicate of https://github.com/KDAB/hotspot/issues/671 but since we don't have any way to reproduce the issue here I'll close this for now. If you think this is not a duplicate, please reopen

**Closed by milianw** 2024-09-02 06:49 UTC
Labels: duplicate, needs_info

**Comment by GitMensch** [comment] 2024-09-02 08:21
only a GitHub UI+API issue:
![duplicate](https://github.com/user-attachments/assets/b683c07f-d469-4aab-8f58-5bc76e955799)

:-)

In any case I try to reproduce the original case and retest with the current appimage of #672

**Comment by GitMensch** [comment] 2024-09-02 08:40
Rechecked - I can't reproduce this specific issue with current continous - so closing as "not reproducible" is the right thing to do (and that issue is unrelated to #671)
