### ISSUE TITLE
No function names

### ISSUE THREAD

**Issue by QbieShay** [KDAB/hotspot#155] opened 2018-10-15 13:11 UTC
Hotspost is unable, for me, to display any data. I can see data if i call perf report, but hotspot doesn't seem to be able to ready the function names. If i call perf report on hotspost generated performance data, perf segfaults when reading. I am assuming there is a mismatch from my perf executable and the one expected by hotspot?

I'm on arch and i just updated everything.

![screenshot_2018-10-15_15-08-50](https://user-images.githubusercontent.com/7917475/46952914-92b2f280-d08c-11e8-80df-fa51b73f5b60.png)

Log:
```
failed to report ElfInfo{localFile="/home/<path>/godot.x11.tools.64.llvm", isFile=true, originalFileName="godot.x11.tools.64.llvm", originalPath="/home/<path>/godot.x11.tools.64.llvm", addr=94211977555968, len=48238592, pgoff=20541440, } for 55af6f74b000 : Cannot report file fragments
```

When opening with perf report on hotspot recorded data:
```
perf: Segmentation fault
-------- backtrace --------
perf(+0x30c2a1)[0x55a3078d52a1]
/usr/lib/libc.so.6(+0x37dff)[0x7f026b77adff]
perf(bfd_demangle+0x11)[0x55a3078fee71]
perf(dso__demangle_sym+0x51)[0x55a307891881]
perf(+0x2a5f6a)[0x55a30786ef6a]
perf(+0x2a629e)[0x55a30786f29e]
perf(dso__parse_addr_inlines+0xab)[0x55a30786fe9b]
perf(+0x269958)[0x55a307832958]
perf(+0x2dc705)[0x55a3078a5705]
perf(+0x2dc7f1)[0x55a3078a57f1]
perf(thread__resolve_callchain+0xfe)[0x55a307837cee]
perf(sample__resolve_callchain+0x5d)[0x55a30782f16d]
perf(hist_entry_iter__add+0x97)[0x55a307861917]
perf(+0x1b295b)[0x55a30777b95b]
perf(+0x2746aa)[0x55a30783d6aa]
perf(+0x277ddc)[0x55a307840ddc]
perf(+0x274d33)[0x55a30783dd33]
perf(+0x27508d)[0x55a30783e08d]
perf(perf_session__process_events+0x2fe)[0x55a30783f7be]
perf(cmd_report+0x186d)[0x55a30777da2d]
perf(+0x21d7f0)[0x55a3077e67f0]
perf(main+0x689)[0x55a3077654f9]
/usr/lib/libc.so.6(__libc_start_main+0xf2)[0x7f026b767222]
perf(_start+0x2d)[0x55a30776576d]
```

(path was manually substituted in the issue)

**Comment by milianw** [comment] 2018-10-16 19:04
this is a duplicate of https://github.com/KDAB/hotspot/issues/125

the perf segfault is caused by a bug in the code which I've fixed some time ago but the patch hasn't been merged upstream yet (it will probably be merged today).

**Closed by milianw** 2018-10-16 19:04 UTC
