### ISSUE TITLE
Perfparser/Hotspot cannot unwind the stack for fork() of created processes

### ISSUE THREAD

**Issue by vtoropov** [KDAB/hotspot#241] opened 2020-05-19 08:02 UTC
The problem was discovered while working with the coremark test.
It concerns multi-threaded mode and USE_FORK model of the test as well as any fork() application.

There is large discrepancy between the values of events costs values for symbols on the Hotspot's Caller/Callee tab and corresponded values of 'perf report'.

The following is 'perf report' output:

![image](https://user-images.githubusercontent.com/65590010/82298594-8ddbc080-99de-11ea-9ef6-3b6f69ac3a1a.png)

And hotspot:

![image](https://user-images.githubusercontent.com/65590010/82298843-e57a2c00-99de-11ea-9d3e-f56ece28eb6a.png)

As you can see the events cost are very different not in favor of hotspot.
coremark.exe was built by the command (make XCFLAGS = "- DMULTITHREAD = 4 -DUSE_FORK = 1")

**Comment by vtoropov** [comment] 2020-05-19 08:22
Hi Milian, could you please appoint me for fixing this bug.
Thanks a lot,
  -- Valentin.

**Comment by milianw** [comment] 2020-05-19 22:05
Hey! Thanks for the report.

First of all: what do you mean by "appoint me for fixing this bug"  - do you want to look into this issue yourself and submit a patch eventually? I.e. should I assign this issue to you?

I'd obviously appreciate that :) But for starters I suggest you create a smaller example that shows this issue which doesn't depend on a larger application like coremark (https://www.eembc.org/coremark/ ?)

**Comment by vtoropov** [comment] 2020-05-20 05:40
Thank you for the response!

Yes, you are right. I’ve meant assigning the issue to me.
I have already prepared a fix for it in my sandbox.

Below is the output of Hotspot for the same perf.data file after my fix.
![image](https://user-images.githubusercontent.com/65590010/82408967-e8385800-9a96-11ea-8037-b00431f8641b.png)

A little bit later I will prepare a small sample.
Thanks,
  --Valentin.

**Comment by milianw** [comment] 2020-05-20 20:38
cool, looking foward to the merge request

but since this will most probably target perfparser, could you please consider to push this patch upstream to the qt gerrit perfparser too?

**Comment by vtoropov** [comment] 2020-05-22 04:46
Milian, 
Yes, I would like to consider to push this patch upstream to the qt gerrit perfparser too.
Could you please point me the following steps to looking forward?

**Comment by milianw** [comment] 2020-05-23 20:54
maybe start with a merge request for kdab/perfparser and then once that's done upstream it - see https://www.qt.io/contribute-to-qt

**Comment by vtoropov** [comment] 2020-05-25 11:16
I created a merge request for KDAB/perfparser.
Should I create a merge request for KDAB/hotspot perfparser too.

**Comment by vtoropov** [comment] 2020-06-01 05:15
Hi, Milian.
I have fix for #178. dwfl_attach_state should be called only for user-level CPU register state and user level stack, allowing stack unwinding.
And what about my merge request for KDAB/perfparser?

**Comment by milianw** [comment] 2020-06-05 15:00
hey there @vtoropov, sorry for the delay - I've now reviewed your other change. Regarding #178 - please sent the patch as a merge request and then I can review it there.

**Comment by milianw** [comment] 2020-06-12 19:38
I've started on a fix for this issue now and will submit it upstream too.

**Comment by milianw** [comment] 2020-06-13 09:42
this issue isn't fully resolved yet, I found a way to reproduce this in a bigger application where the order in which we process events is important - will reopen

**Closed** 2020-06-13 09:57 UTC
Labels: bug
